<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Version>1.0</Version>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <StartupObject>SMTAlert.App</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|x64'">
    <OutputPath>bin\x64\Debug\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|x64'">
    <OutputPath>bin\x64\Release\</OutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PointyHatGames.EVEStandard" Version="4.0.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Sounds\woop.mp3">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data\Systems.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data\ShipTypes.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="data\ShipTypesCN.dat">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="CopySMTDataFiles" AfterTargets="AfterBuild">
    <MakeDir Directories="$(TargetDir)data" />
    <Copy SourceFiles="..\..\SMT\EVEData\data\Systems.dat"
          DestinationFolder="$(TargetDir)data"
          Condition="Exists('..\..\SMT\EVEData\data\Systems.dat')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="..\..\SMT\EVEData\data\ShipTypes.dat"
          DestinationFolder="$(TargetDir)data"
          Condition="Exists('..\..\SMT\EVEData\data\ShipTypes.dat')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="..\..\SMT\EVEData\data\ShipTypesCN.dat"
          DestinationFolder="$(TargetDir)data"
          Condition="Exists('..\..\SMT\EVEData\data\ShipTypesCN.dat')"
          SkipUnchangedFiles="true" />
  </Target>

  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>
